simplification

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,53 +2,72 @@ sudo: required
 services: docker
 
 env:
-  # - distro: rhel
-  #   version: 7
-  #   container: "registry.access.redhat.com/rhel7"
-  #   init: /usr/lib/systemd/systemd
-  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
-
-  - distro: centos
+  - distribution: centos
     version: 7
-    container: "centos:7"
-    init: /usr/lib/systemd/systemd
-    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
 
 before_install:
-  # Pull container.
-  - 'docker pull ${container}'
-  - 'if [ ${distro} = "rhel" ]; then
-        docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
-     else
-        docker build --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
-     fi'
+  - 'sudo docker pull ${distribution}:${version}'
+  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'
 
 script:
-  - container_id=$(date +%s)
-
-  # Run container in detached state.
-  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro --name $container_id ${run_opts} ${distro}-${version}:ansible "${init}"'
-
-  # Ansible syntax check.
-  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --syntax-check
-
-  # Test role.
-  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars_travis.yml" -vv
-
-  # Test role idempotence.
-  - idempotence_log=$(mktemp)
-
-  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars_travis.yml" -vv | tee -a $idempotence_log
+  - container_id=$(mktemp)
+  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/oracledb_preinstall:ro ${distribution}-${version}:ansible > "${container_id}"'
+  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/oracledb_preinstall/travis/test.yml --syntax-check'
+  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/oracledb_preinstall/travis/test.yml'
   - >
-    tail $idempotence_log
-    | grep -q "changed=0.*failed=0"
-    && (echo "Idempotence test: pass" && exit 0)
-    || (echo "Idempotence test: fail" && exit 1)
-
-  # Deregister
-  - 'if [ ${distro} = "rhel" ]; then
-        docker exec $container_id subscription-manager unregister;
-     fi'
-
-notifications:
-  webhooks: https://galaxy.ansible.com/api/v1/notifications/
+    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/oracledb_preinstall/travis/test.yml
+    | grep -q 'changed=0.*failed=0'
+    && (echo 'Idempotence test: pass' && exit 0)
+    || (echo 'Idempotence test: fail' && exit 1)
+  - 'sudo docker rm -f "$(cat ${container_id})"'
+#env:
+#  # - distro: rhel
+#  #   version: 7
+#  #   container: "registry.access.redhat.com/rhel7"
+#  #   init: /usr/lib/systemd/systemd
+#  #   run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
+#
+#  - distro: centos
+#    version: 7
+#    container: "centos:7"
+#    init: /usr/lib/systemd/systemd
+#    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
+#
+#before_install:
+#  # Pull container.
+#  - 'docker pull ${container}'
+#  - 'if [ ${distro} = "rhel" ]; then
+#        docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
+#     else
+#        docker build --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests;
+#     fi'
+#
+#script:
+#  - container_id=$(date +%s)
+#
+#  # Run container in detached state.
+#  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro --name $container_id ${run_opts} ${distro}-${version}:ansible "${init}"'
+#
+#  # Ansible syntax check.
+#  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --syntax-check
+#
+#  # Test role.
+#  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars_travis.yml" -vv
+#
+#  # Test role idempotence.
+#  - idempotence_log=$(mktemp)
+#
+#  - docker exec --tty $container_id ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars "@/etc/ansible/roles/role_under_test/tests/extra_vars_travis.yml" -vv | tee -a $idempotence_log
+#  - >
+#    tail $idempotence_log
+#    | grep -q "changed=0.*failed=0"
+#    && (echo "Idempotence test: pass" && exit 0)
+#    || (echo "Idempotence test: fail" && exit 1)
+#
+#  # Deregister
+#  - 'if [ ${distro} = "rhel" ]; then
+#        docker exec $container_id subscription-manager unregister;
+#     fi'
+#
+#notifications:
+#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
